### ISSUE TITLE
Can support `Copy` and `Undo` ❓	

### ISSUE THREAD

**Issue by dnknn** [qufighter/QueryParser#1]
null

**Comment by qufighter** [comment]
I like the restore idea.  Multi-cell-copy does exist; you have to activate grid mode `⊟` to achieve it though.  Then you can drag to select consecutive cells, and must copy via keyboard command.  Can add a button.  Thanks for the feature suggestions!

**Comment by dnknn** [comment]
Thank you very much for your reply:)



A few days ago, I tested many related extensions, and finally gave up everything else, leaving only your extensions. because 👇
![image](https://user-images.githubusercontent.com/10995302/87886823-91c5a680-ca52-11ea-956a-7fc18dd2b097.png)

You can refer to it, there are also good functions. 👇
🗑Easy URL Params	 2015	
	https://chrome.google.com/webstore/detail/jhhjlajfdkofbnhbcjcddngfehfihfln
	https://github.com/samsel/easy-url-params
>Can't display `?` `&` these important symbols, and also does not support `/` ⋯⋯  `/ `partial viewing and editing.
But the interface UI is still very good.

🗑URI Splitter
https://chrome.google.com/webstore/detail/fdfikmgcjjhkdpejagohhojbopclfckn
https://github.com/denilsonsa/crx-uri-splitter/
>Abundant shortcut keys support, also can 🗚 customize font-size or font-family.
but Still no feeling.


🗑Url Editor PRO		2020
https://chrome.google.com/webstore/detail/maoigfcibanjdgnepaiiadjhgmejclea
https://github.com/maxwroc/UrlEditorPro
>The font is also very small, the icon is a pen 🖊 appearance, easy to confuse with the text filling
It also supports many shortcut keys. I’m just curious why we need to integrate complex redirection functions,
And it also comes with automatic refresh, I don't understand.

**Comment by dnknn** [comment]
> to activate grid mode `⊟` to achieve it though

👍OK,Yes i get it 💪 Thanks♪(･ω･)ﾉ

### is `◫` no `⊟` ^_^

----
> I like the restore idea.

About **restore** / **undo** / **Redo**
### ❶ Support Ctrl+🆉 to Undo, Ctrl+Shift+🆉 / Ctrl+🆈 to Redo
>☝Because they are 🌌**global** **standard** ⌨**Hotkey**.

### ❷ In addition to Hotkey, buttons can also be placed.
![0720083402](https://user-images.githubusercontent.com/10995302/87889360-c726c000-ca63-11ea-8b64-85587f6d0d1d.png)


### ❸ Support Undo/Redo in turn.
> For example, I delete fields 1, 2, 3, 4, then can restore them one by one,vice versa.

### ❹ If possible, add another button to restore the popup URL with one click.
> When Popup is started, the URL is `https://www.xx.com/s?ie=8&f=5&bp=1&ch=&tn=333`
Then change it, and finally want to restore the URL at the beginning.
Then click the button, it will be back to `https://www.xx.com/s?ie=8&f=5&bp=1&ch=&tn=333`


![0720085018](https://user-images.githubusercontent.com/10995302/87889812-0f46e200-ca66-11ea-8341-c69dd07cb1d8.png)


sorry for my English🤦🙈
