### ISSUE TITLE
can you add `autocomplete="off"`

### ISSUE THREAD

**Issue by dnknn** [qufighter/QueryParser#2]
`autocomplete="off"`
Because there is no need,  the most important problem is that it will disturb each other's normal input operations.
![image](https://user-images.githubusercontent.com/10995302/87886910-37791580-ca53-11ea-9e0f-a4757a53694c.png)

`URI Splitter`  have this option
chrome.google.com/webstore/detail/fdfikmgcjjhkdpejagohhojbopclfckn

If you don’t want to add setting options, you should change to disabled by default, 
Add in HTML: `autocomplete="off"`

**Comment by qufighter** [comment]
I don't think autocomplete can be disabled anymore these days.  It has caused some headaches but it is for the best.... slowly the bugs are being worked out where the dismissal of the auto complete dropdown doesn't dismiss the interactive field UX it is blocking.  But I also think it's not a problem the chrome popup itself is it?

Short of just using content editable I don't think there is really a great way to fully avoid autocomplete.  If you are using an input field there should be some way for the user to get to the autocomplete feature if they want it, and a way to dismiss autocomplete without breaking any custom modal action the webpage has active.

I hate to say it but I think it's outside the scope of what this extension is intended to do... if there is a field within the extension where autocomplete is problematic we can try to take a look.
