### ISSUE TITLE
Can support the parameter parsing after manually typing the URL❓

### ISSUE THREAD

**Issue by dnknn** [qufighter/QueryParser#3]

**Comment by qufighter** [comment]
I don't think a URL in the address bar that has not yet been navigated to can be captured.  After redirect though, you should be able to get the result.  As for before redirect... maybe we can intercept the redirect and hold onto it somehow... but we'd probably need webNavigation or webRequest permission to do so.

https://developer.chrome.com/extensions/webNavigation
https://developer.chrome.com/extensions/webRequest

If the omnibox api allowed it, maybe we could query what is typed there, but as far as I know that's not possible!
https://developer.chrome.com/extensions/omnibox

So I think we might be at a loss for that core feature... however the button to grab whatever is currently there (reset) sort of already exists, by closing the popup and then accessing it again!

**Comment by dnknn** [comment]
I mean the URL before the redirect,
In other words, it does not currently support parsing parameters of **manually** typed URL.

**Comment by qufighter** [comment]
Yes, manually typed in the address bar, prior to navigation....
I originally tried to achieve this, I don't think it is yet possible unless the omnibox api or something like it will support it.

My vision was to synchronize from whatever is typed when the popup is opened (prior to navigation, so I could fully customize and then navigate) but I could not achieve that at the time when this extension was written.  I even wanted to update the address bar without navigating, and then edit more, then return tot he popup and edit even further.  So far that does not seem possible given current APIs unless I missed something!

That combined with a redirect would be especially annoying!  It is one thing when you control the web server and can change it but quite another when you cannot!

**Comment by dnknn** [comment]
ok Thanks
